### PR TITLE
add 1.6 example with labels and pass unique leader elect name

### PR DESCRIPTION
**Pull request by poidag-zz**
relates to #18. Not sure if we want to default in flag configuration.

### CODE REVIEW

**Comment by thebsdbox** [comment]
Without specifying an actual resource name, i'm not sure what the name will default too.. perhaps something like 
`- --leader-elect-resource-name=plndr-cloud-controller` ?

**Comment by poidag-zz** [comment]
`plndr-cloud-controller` sounds good. I think maintaining an example install that shows passing through of flags to the cloud controller manager lib would be a lot less friction for now without defining a customer leaderElectionConfig WDYT? @thebsdbox

**Comment by poidag-zz** [comment]
Also, Is there a plan to transition this from a `Pod` to a `Deployment`. Delete operations for pods are often performed as a part of remediation and debugging and delete on a single pod could leave the controller inadvertently removed from the cluster. Let me know and I'll create a separate issue for this.

**Comment by thebsdbox** [comment]
Yes, we should move to a deployment!

**Pull request merged**
